import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {type: 'autogenerated', dirName: '.'},
  ],
  apiSidebar: [
    {type: 'autogenerated', dirName: 'api'},
  ],
  frontendSidebar: [
    {type: 'autogenerated', dirName: 'frontend'},
  ],
};

export default sidebars;
